#!/bin/bash

if [[ -z "$1" ]]
then
  echo 'Missing option arg'
  exit 1
fi

if [[ $1 -eq 1 ]]
then
  rm pa1/a.out
  rm pa1/events.log
  rm pa1/pipes.log

  tar -czvf pa1.tar.gz pa1
  mv pa1.tar.gz archives/

  cp pa1/* moss_faker/1/my/
fi
