#!/bin/bash

if [[ -z "$1" ]]
then
  echo 'Missing option arg'
  exit 1
fi

rm pa$1/a.out
rm pa$1/events.log
rm pa$1/pipes.log

tar -czvf pa$1.tar.gz pa$1
mv pa$1.tar.gz archives/

cp pa$1/* moss_faker/$1/my/

rm moss_faker/$1/my/lib*
rm moss_faker/$1/my/bank*
rm moss_faker/$1/my/pa2345*
rm moss_faker/$1/my/ipc.h
